// <auto-generated />
namespace Proiect_Tudose_Baias.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class option111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(option111));
        
        string IMigrationMetadata.Id
        {
            get { return "202101080825448_option111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
